version: '3'

services:
  backend:
    image: alinaverse-backend
    build:
      context: .
      dockerfile: AlinaverseAPI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      JwtSettings__SecretKey: "3ZcRUst4DM9M24kree5uupQyLmL6pRARw7xxuPAtH"
      JwtSettings__LifeSpan: 30
      JwtSettings__RefreshTokenLifeSpan: 30
      JwtSettings__ValidIssuer: "Alinaverse"
      JwtSettings__ValidAudience: "http://localhost:80"
      ConnectionStrings__PostgreSQL: Host=postgres;Port=5432;Username=postgres;Password=root;Database=alinaverse;


  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5444:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

